h264nal: make g++ happy
This broke with g++ (GCC) 15.0.1.

Tested:

Before:
```
$ cd build
$ make -j
...
../include/h264_utils.h:17:57: error: use of undeclared identifier 'uint8_t' [clang-diagnostic-error]
   17 |   static int ReadFile(const char* filename, std::vector<uint8_t>& buffer);
```

After:
```
$ cd build
$ make -j
...
[100%] Built target h264_nal_unit_header_svc_extension_parser_unittest
make[1]: Leaving directory 'h264nal/build'
/usr/local/lib64/python3.12/site-packages/cmake/data/bin/cmake -E cmake_progress_start h264nal/build/CMakeFiles 0
```

Also tested with clang++ 20.1.2.