h264nal: svc: ensure seq_parameter_set_svc_extension is defined
slice_header_in_scalable_extension() (defined inside
slice_layer_extension_rbsp()) requires accessing
seq_parameter_set_svc_extension(() inside the subset SPS.

Tested:

Fixed fuzz crashes.

```
$ ./build/fuzz/h264_bitstream_parser_fuzzer ./fuzz/corpus/h264_bitstream_parser_fuzzer/crash-ad4b7f08a62ca2f39069f8e40612b330620890f8
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 2304365142
INFO: Loaded 1 modules   (2195 inline 8-bit counters): 2195 [0x6621b0, 0x662a43),
INFO: Loaded 1 PC tables (2195 PCs): 2195 [0x613e90,0x61c7c0),
./build/fuzz/h264_bitstream_parser_fuzzer: Running 1 inputs 1 time(s) each.
Running: ./fuzz/corpus/h264_bitstream_parser_fuzzer/crash-ad4b7f08a62ca2f39069f8e40612b330620890f8
error: cannot ParseNalUnitHeader in nal unit
Could not parse a buffer into a NalUnit
Executed ./fuzz/corpus/h264_bitstream_parser_fuzzer/crash-ad4b7f08a62ca2f39069f8e40612b330620890f8 in 4 ms
***
*** NOTE: fuzzing was not performed, you have only
***       executed the target code on a fixed set of inputs.
***

$ ./build/fuzz/h264_rtp_parser_fuzzer fuzz/corpus/h264_rtp_parser_fuzzer/crash-d416eddcdc0202d6085bc2c519c6f99e5eaf8163
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 3552045936
INFO: Loaded 1 modules   (2552 inline 8-bit counters): 2552 [0x674a40, 0x675438),
INFO: Loaded 1 PC tables (2552 PCs): 2552 [0x622058,0x62bfd8),
./build/fuzz/h264_rtp_parser_fuzzer: Running 1 inputs 1 time(s) each.
Running: fuzz/corpus/h264_rtp_parser_fuzzer/crash-d416eddcdc0202d6085bc2c519c6f99e5eaf8163
error: unimplemented ref_pic_list_mvc_modification in pps
error: unimplemented ref_pic_list_mvc_modification in pps
Executed fuzz/corpus/h264_rtp_parser_fuzzer/crash-d416eddcdc0202d6085bc2c519c6f99e5eaf8163 in 1 ms
***
*** NOTE: fuzzing was not performed, you have only
***       executed the target code on a fixed set of inputs.
***

$ ./build/fuzz/h264_rtp_stapa_parser_fuzzer fuzz/corpus/h264_rtp_stapa_parser_fuzzer/crash-7a3fe263c68d38628478aac7c9f8bc46d63f597f
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 3405027087
INFO: Loaded 1 modules   (2264 inline 8-bit counters): 2264 [0x65f540, 0x65fe18),
INFO: Loaded 1 PC tables (2264 PCs): 2264 [0x610e00,0x619b80),
./build/fuzz/h264_rtp_stapa_parser_fuzzer: Running 1 inputs 1 time(s) each.
Running: fuzz/corpus/h264_rtp_stapa_parser_fuzzer/crash-7a3fe263c68d38628478aac7c9f8bc46d63f597f
Executed fuzz/corpus/h264_rtp_stapa_parser_fuzzer/crash-7a3fe263c68d38628478aac7c9f8bc46d63f597f in 1 ms
***
*** NOTE: fuzzing was not performed, you have only
***       executed the target code on a fixed set of inputs.
***
```