h264nal: fuzz: fix crashes
Issue was the possibility that `svc_extension_flag` is defined but
there are not enough bits for `nal_unit_header_svc_extension`.

```
$ ../build/fuzz/h264_bitstream_parser_fuzzer corpus/h264_bitstream_parser_fuzzer/crash-b5c360a2c271c46ad5c6d9b10baf53578eace01a
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 2289732695
INFO: Loaded 1 modules   (1866 inline 8-bit counters): 1866 [0x642c90, 0x6433da),
INFO: Loaded 1 PC tables (1866 PCs): 1866 [0x5f8af0,0x5fff90),
../build/fuzz/h264_bitstream_parser_fuzzer: Running 1 inputs 1 time(s) each.
Running: corpus/h264_bitstream_parser_fuzzer/crash-b5c360a2c271c46ad5c6d9b10baf53578eace01a
error: unimplemented chroma_format_idc and scaling_list in pps
Executed corpus/h264_bitstream_parser_fuzzer/crash-b5c360a2c271c46ad5c6d9b10baf53578eace01a in 0 ms
***
*** NOTE: fuzzing was not performed, you have only
***       executed the target code on a fixed set of inputs.
***

$ ../build/fuzz/h264_rtp_parser_fuzzer corpus/h264_rtp_parser_fuzzer/crash-45f0fe8af5a2aecc9d5e4e8fd3e2e94c10d95c5a
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 3360184474
INFO: Loaded 1 modules   (2223 inline 8-bit counters): 2223 [0x65b520, 0x65bdcf),
INFO: Loaded 1 PC tables (2223 PCs): 2223 [0x60cd78,0x615868),
../build/fuzz/h264_rtp_parser_fuzzer: Running 1 inputs 1 time(s) each.
Running: corpus/h264_rtp_parser_fuzzer/crash-45f0fe8af5a2aecc9d5e4e8fd3e2e94c10d95c5a
Executed corpus/h264_rtp_parser_fuzzer/crash-45f0fe8af5a2aecc9d5e4e8fd3e2e94c10d95c5a in 0 ms
***
*** NOTE: fuzzing was not performed, you have only
***       executed the target code on a fixed set of inputs.
***

$ ../build/fuzz/h264_rtp_single_parser_fuzzer corpus/h264_rtp_single_parser_fuzzer/crash-1d6c14e93e9864959af1f5a00eda316009b8ab8b
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 493002695
INFO: Loaded 1 modules   (1674 inline 8-bit counters): 1674 [0x633f80, 0x63460a),
INFO: Loaded 1 PC tables (1674 PCs): 1674 [0x5ecee0,0x5f3780),
../build/fuzz/h264_rtp_single_parser_fuzzer: Running 1 inputs 1 time(s) each.
Running: corpus/h264_rtp_single_parser_fuzzer/crash-1d6c14e93e9864959af1f5a00eda316009b8ab8b
Executed corpus/h264_rtp_single_parser_fuzzer/crash-1d6c14e93e9864959af1f5a00eda316009b8ab8b in 0 ms
***
*** NOTE: fuzzing was not performed, you have only
***       executed the target code on a fixed set of inputs.
***

$ ../build/fuzz/h264_rtp_stapa_parser_fuzzer corpus/h264_rtp_stapa_parser_fuzzer/crash-427ea0a50649cd400ad5edc20f0afdc6b4dd824a
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 2806714429
INFO: Loaded 1 modules   (1935 inline 8-bit counters): 1935 [0x646020, 0x6467af),
INFO: Loaded 1 PC tables (1935 PCs): 1935 [0x5fbb20,0x603410),
../build/fuzz/h264_rtp_stapa_parser_fuzzer: Running 1 inputs 1 time(s) each.
Running: corpus/h264_rtp_stapa_parser_fuzzer/crash-427ea0a50649cd400ad5edc20f0afdc6b4dd824a
Executed corpus/h264_rtp_stapa_parser_fuzzer/crash-427ea0a50649cd400ad5edc20f0afdc6b4dd824a in 0 ms
***
*** NOTE: fuzzing was not performed, you have only
***       executed the target code on a fixed set of inputs.
***

$ ../build/fuzz/h264_nal_unit_parser_fuzzer corpus/h264_nal_unit_parser_fuzzer/crash-9e0fc30799fc088147e0e5f023f73a5d2edcec45
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1381041379
INFO: Loaded 1 modules   (1680 inline 8-bit counters): 1680 [0x630fc0, 0x631650),
INFO: Loaded 1 PC tables (1680 PCs): 1680 [0x5eae50,0x5f1750),
../build/fuzz/h264_nal_unit_parser_fuzzer: Running 1 inputs 1 time(s) each.
Running: corpus/h264_nal_unit_parser_fuzzer/crash-9e0fc30799fc088147e0e5f023f73a5d2edcec45
Executed corpus/h264_nal_unit_parser_fuzzer/crash-9e0fc30799fc088147e0e5f023f73a5d2edcec45 in 0 ms
***
*** NOTE: fuzzing was not performed, you have only
***       executed the target code on a fixed set of inputs.
***
```